/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int dynamics_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dynamics_func_alloc_mem(void);
int dynamics_func_init_mem(int mem);
void dynamics_func_free_mem(int mem);
int dynamics_func_checkout(void);
void dynamics_func_release(int mem);
void dynamics_func_incref(void);
void dynamics_func_decref(void);
casadi_int dynamics_func_n_in(void);
casadi_int dynamics_func_n_out(void);
casadi_real dynamics_func_default_in(casadi_int i);
const char* dynamics_func_name_in(casadi_int i);
const char* dynamics_func_name_out(casadi_int i);
const casadi_int* dynamics_func_sparsity_in(casadi_int i);
const casadi_int* dynamics_func_sparsity_out(casadi_int i);
int dynamics_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dynamics_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dynamics_func_SZ_ARG 9
#define dynamics_func_SZ_RES 2
#define dynamics_func_SZ_IW 7
#define dynamics_func_SZ_W 545
int jac_dynamics_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int jac_dynamics_func_alloc_mem(void);
int jac_dynamics_func_init_mem(int mem);
void jac_dynamics_func_free_mem(int mem);
int jac_dynamics_func_checkout(void);
void jac_dynamics_func_release(int mem);
void jac_dynamics_func_incref(void);
void jac_dynamics_func_decref(void);
casadi_int jac_dynamics_func_n_in(void);
casadi_int jac_dynamics_func_n_out(void);
casadi_real jac_dynamics_func_default_in(casadi_int i);
const char* jac_dynamics_func_name_in(casadi_int i);
const char* jac_dynamics_func_name_out(casadi_int i);
const casadi_int* jac_dynamics_func_sparsity_in(casadi_int i);
const casadi_int* jac_dynamics_func_sparsity_out(casadi_int i);
int jac_dynamics_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int jac_dynamics_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define jac_dynamics_func_SZ_ARG 10
#define jac_dynamics_func_SZ_RES 6
#define jac_dynamics_func_SZ_IW 19
#define jac_dynamics_func_SZ_W 1070
int fwd1_dynamics_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int fwd1_dynamics_func_alloc_mem(void);
int fwd1_dynamics_func_init_mem(int mem);
void fwd1_dynamics_func_free_mem(int mem);
int fwd1_dynamics_func_checkout(void);
void fwd1_dynamics_func_release(int mem);
void fwd1_dynamics_func_incref(void);
void fwd1_dynamics_func_decref(void);
casadi_int fwd1_dynamics_func_n_in(void);
casadi_int fwd1_dynamics_func_n_out(void);
casadi_real fwd1_dynamics_func_default_in(casadi_int i);
const char* fwd1_dynamics_func_name_in(casadi_int i);
const char* fwd1_dynamics_func_name_out(casadi_int i);
const casadi_int* fwd1_dynamics_func_sparsity_in(casadi_int i);
const casadi_int* fwd1_dynamics_func_sparsity_out(casadi_int i);
int fwd1_dynamics_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int fwd1_dynamics_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define fwd1_dynamics_func_SZ_ARG 13
#define fwd1_dynamics_func_SZ_RES 2
#define fwd1_dynamics_func_SZ_IW 7
#define fwd1_dynamics_func_SZ_W 756
#ifdef __cplusplus
} /* extern "C" */
#endif
